export const STATUS_FIELDS = [
    {
      id: 1,
      name: "能力値",
      STR: 0,
      CON: 0,
      POW: 0,
      DEX: 0,
      APP: 0,
      SIZ: 0,
      INT: 0,
      EDU: 0,
      HP: 0,
      MP: 0
    },
    {
      id: 2,
      name: "増加分",
      STR: 0,
      CON: 0,
      POW: 0,
      DEX: 0,
      APP: 0,
      SIZ: 0,
      INT: 0,
      EDU: 0,
      HP: 0,
      MP: 0
    },
    {
      id: 3,
      name: "一時的",
      STR: 0,
      CON: 0,
      POW: 0,
      DEX: 0,
      APP: 0,
      SIZ: 0,
      INT: 0,
      EDU: 0,
      HP: 0,
      MP: 0
    },
    {
      id: 4,
      name: "現在値",
      STR: 0,
      CON: 0,
      POW: 0,
      DEX: 0,
      APP: 0,
      SIZ: 0,
      INT: 0,
      EDU: 0,
      HP: 0,
      MP: 0
    },
  ];

export const BASIC_SKILLS_FIELDS = [
  {
    id: 101,
    step: "あ",
    skill_name: "言いくるめ",
    init_point: 5,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
  }, 
  {
    id: 102,
    step: "あ",
    skill_name: "医学",
    init_point: 5,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
  },
  {
    id: 3,
    step: "あ",
    skill_name: "運転(自動車)",
    character_id: 1,
    init_point: 20,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 4,
    step: "あ",
    skill_name: "運転",
    character_id: 1,
    init_point: 20,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 5,
    step: "あ",
    skill_name: "応急手当",
    character_id: 30,
    init_point: 5,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 6,
    step: "あ",
    skill_name: "オカルト",
    character_id: 5,
    init_point: 5,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 7,
    step: "か",
    skill_name: "回避",
    character_id: 1,
    init_point: 0,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 8,
    step: "か",
    skill_name: "化学",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 9,
    step: "か",
    skill_name: "鍵開け",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 10,
    step: "か",
    skill_name: "隠す",
    character_id: 1,
    init_point: 15,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 11,
    step: "か",
    skill_name: "隠れる",
    character_id: 1,
    init_point: 10,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 12,
    step: "か",
    skill_name: "機械修理",
    character_id: 1,
    init_point: 20,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 13,
    step: "か",
    skill_name: "聞き耳",
    character_id: 1,
    init_point: 25,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 14,
    step: "か",
    skill_name: "クトゥルフ神話",
    character_id: 1,
    init_point: 0,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 15,
    step: "か",
    skill_name: "芸術",
    character_id: 1,
    init_point: 5,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 16,
    step: "か",
    skill_name: "経理",
    character_id: 1,
    init_point: 10,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 17,
    step: "か",
    skill_name: "考古学",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 18,
    step: "か",
    skill_name: "コンピューター",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 19,
    step: "さ",
    skill_name: "忍び歩き",
    character_id: 1,
    init_point: 10,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 20,
    step: "さ",
    skill_name: "写真術",
    character_id: 1,
    init_point: 10,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 21,
    step: "さ",
    skill_name: "重機械操作",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 22,
    step: "さ",
    skill_name: "乗馬",
    character_id: 1,
    init_point: 5,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 23,
    step: "さ",
    skill_name: "信用",
    character_id: 1,
    init_point: 15,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 24,
    step: "さ",
    skill_name: "心理学",
    character_id: 1,
    init_point: 5,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 25,
    step: "さ",
    skill_name: "人類学",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 26,
    step: "さ",
    skill_name: "水泳",
    character_id: 1,
    init_point: 25,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 27,
    step: "さ",
    skill_name: "制作",
    character_id: 1,
    init_point: 5,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 28,
    step: "さ",
    skill_name: "精神分析",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 29,
    step: "さ",
    skill_name: "生物学",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 30,
    step: "さ",
    skill_name: "説得",
    character_id: 1,
    init_point: 15,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 31,
    step: "さ",
    skill_name: "操縦",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 32,
    step: "た",
    skill_name: "地質学",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 33,
    step: "た",
    skill_name: "跳躍",
    character_id: 1,
    init_point: 25,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 34,
    step: "た",
    skill_name: "追跡",
    character_id: 1,
    init_point: 10,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 35,
    step: "た",
    skill_name: "電気修理",
    character_id: 1,
    init_point: 10,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 36,
    step: "た",
    skill_name: "電子工学",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 37,
    step: "た",
    skill_name: "天文学",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 38,
    step: "た",
    skill_name: "投擲",
    character_id: 1,
    init_point: 25,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 39,
    step: "た",
    skill_name: "登攀",
    character_id: 40,
    init_point: 5,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 40,
    step: "た",
    skill_name: "図書館",
    character_id: 1,
    init_point: 25,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 41,
    step: "な",
    skill_name: "ナビゲート",
    character_id: 1,
    init_point: 10,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 42,
    step: "な",
    skill_name: "値切り",
    character_id: 1,
    init_point: 5,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 43,
    step: "は",
    skill_name: "博物学",
    character_id: 1,
    init_point: 10,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 44,
    step: "は",
    skill_name: "物理学",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 45,
    step: "は",
    skill_name: "変装",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 46,
    step: "は",
    skill_name: "法律",
    character_id: 1,
    init_point: 5,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 47,
    step: "は",
    skill_name: "ほかの言語",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 48,
    step: "は",
    skill_name: "母国語",
    character_id: 1,
    init_point: 0,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 49,
    step: "ま",
    skill_name: "マーシャルアーツ",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 50,
    step: "ま",
    skill_name: "目星",
    character_id: 1,
    init_point: 25,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 51,
    step: "や",
    skill_name: "薬学",
    character_id: 1,
    init_point: 1,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 52,
    step: "ら",
    skill_name: "歴史",
    character_id: 1,
    init_point: 20,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
];

export const BATTLE_SKILLS_FIELDS = [

{
    id: 53,
    step: "か",
    skill_name: "拳銃",
    character_id: 1,
    init_point: 20,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 54,
    step: "さ",
    skill_name: "サブマシンガン",
    character_id: 1,
    init_point: 15,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 55,
    step: "さ",
    skill_name: "ショットガン",
    character_id: 1,
    init_point: 30,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 56,
    step: "ま",
    skill_name: "マシンガン",
    character_id: 1,
    init_point: 15,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 57,
    step: "ら",
    skill_name: "ライフル",
    character_id: 1,
    init_point: 25,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 58,
    step: "か",
    skill_name: "キック",
    character_id: 1,
    init_point: 25,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 59,
    step: "か",
    skill_name: "組付き",
    character_id: 1,
    init_point: 25,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 60,
    step: "か",
    skill_name: "こぶし",
    character_id: 1,
    init_point: 50,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
},
{
    id: 61,
    step: "さ",
    skill_name: "頭突き",
    character_id: 1,
    init_point: 10,
    job_point: 0,
    concern_point: 0,
    grow: 0,
    other: 0,
    summary: 0,
    init_flag: true
}
];

export const WEAPON_DATA_FIELDS = [

    {
        id: 1,
        weapon: "拳銃",
        skill_point: 1,
        damage: "2D6",
        range: "20m",
        number_of_attacks: 0,
        ammunition_capacity: 0,
        failure_value: 0,
        endurance: 0
    },
    ];

export const BELONGINGS_DATA_FIELDS = [

    {
        id: 1,
        item: "筆記用具",
        quantity: 1,
        detail: "なんかいろいろ入っている"
    },
    ];

export const HISTORY_DATA_FIELDS = [

    {
        id: 1,
        scenario: "毒入りスープ",
        remarks: "メンバー"
    },
    ];

export const CHARACTER_DATA_FIELDS = [

    {
        id: 1,
        profile: "性格",
        datum: "気まぐれでうそつき"
    },
    ];

export const WEALTH_DATA_FIELDS = [

    {
        id: 1,
        wealth: "1000万",
        remarks: "20万"
    },
    ];